### ISSUE TITLE
RESTFul web service. bean of type 'graphql.GraphQL' not found

### ISSUE THREAD

**Issue by Latsode** [graphql-java-generator/graphql-maven-plugin-project#109]
Hello,

So whenever I remove  web-application-type: none from application.yml and start the application I get this error :

Field graphQL in graphql.spring.web.servlet.components.DefaultGraphQLInvocation required a bean of type 'graphql.GraphQL' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'graphql.GraphQL' in your configuration.

Process finished with exit code 1

Latsode

**Comment by etienne-sf** [comment]
Ok, noted.

I'll check that.

BTW, this `web-application-type` should be necessary. But it is  :(

Etienne

**Comment by Latsode** [comment]
Well `web-application-type = none` is necessary if you dont need web server but I am currently building RESTful web API so I need my web server to start and send requests to it . 

Btw I magically found how to fix this problem but still have no idea why it happens . So in my first version I was using this dependency
 ```xml
         <dependency>
            <groupId>com.graphql-java-generator</groupId>
            <artifactId>graphql-java-runtime</artifactId>
            <version>${graphql-maven-plugin.version}</version>
        </dependency>
```
then for some weird reason after going through examples I swapped that dependency with 
```xml
        <dependency>
            <groupId>com.graphql-java-generator</groupId>
            <artifactId>graphql-java-client-dependencies</artifactId>
            <type>pom</type>
            <version>${graphql-maven-plugin.version}</version>
        </dependency>
```
and now everything is working perfectly fine , so there must be some kind of issue with `graphql-java-runtime` but I have no idea what it is . I hope this helps .

Latsode

**Comment by etienne-sf** [comment]
Yes, that's strange. And it's a good starting point. 

BTW, I need to rethink the management of the dependencies. 

But it will be rather complex because of the number of combinations : client/server, pojo only, with or without the copy of runtime sources...

**Comment by etienne-sf** [comment]
Hello,

I removed the ´web-application-type: none´ parameter and I confirm there is an issue with Spring dependencies. 

But I didn't got the exact same error as yours. 

For me, it's a chain of missing dependencies, where the real missing bean is the ´ReactiveClientRegistrationRepository´. 

Can you check if it's the same for you, or if you encountered some different issue ?

Étienne

**Comment by etienne-sf** [comment]
FYI

This issue is due to server dependencies being lixed with the client dependencies.

This is solved in my last commit, which properly separate client and server dependencies. It will be available in the next release.

**Comment by Latsode** [comment]
Hello,
I am sorry for such late reply . I upgraded to 1.18 and my issue is still there .Problem is with this dependency 
```
        <dependency>
            <groupId>com.graphql-java-generator</groupId>
            <artifactId>graphql-java-runtime</artifactId>
            <version>${graphql-maven-plugin.version}</version>
        </dependency>
```
Whenever I use that I get this error
```
Field graphQL in graphql.spring.web.servlet.components.DefaultGraphQLInvocation required a bean of type 'graphql.GraphQL' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'graphql.GraphQL' in your configuration. 
```
When I swap mentioned dependency with this one
```
        <dependency>
            <groupId>com.graphql-java-generator</groupId>
            <artifactId>graphql-java-client-dependencies</artifactId>
            <type>pom</type>
            <version>${graphql-maven-plugin.version}</version>
        </dependency>
```
I have no issues whatsoever . So there must be something wrong with `graphql-java-runtime`. 

You can replicate same issue if you clone this generator-problem branch from my sample `https://github.com/Latsode/spring-graphql-shopify-client-sample/tree/generator-problem`. 

Latsode

**Comment by Latsode** [comment]
Also forgot to mention that master branch has no more problems whatsoever so we can freely close the issue #107 and reference my sample's master branch without any problems.

**Comment by etienne-sf** [comment]
Thanks for the comment.
:)

I improved the dependencies separation between the client and the server mode. This sepatation solves the "'graphql.GraphQL' not found" issue. I'll close it when I do the release.

I'm currently working on a Gradle issue, that I want to release in the same time

Etienne

**Comment by etienne-sf** [comment]
Done in the 1.18.1 release

**Comment by amar-shinde** [comment]
Hello,

I recently tried my hand with this library to generate client code. I was keen to make use of repositories on client side to query GraphQL APIs.
Below is my dependency: (graphql-maven-plugin.version: 1.18)

    <dependency>
        <groupId>com.graphql-java-generator</groupId>
	<artifactId>graphql-java-runtime</artifactId>
	<version>${graphql-maven-plugin.version}</version>	
   </dependency>
   
   But I still face the same issue, 
   
   Field graphQL in graphql.spring.web.servlet.components.DefaultGraphQLInvocation required a bean of type 'graphql.GraphQL' that could not be found.
The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)
Action:
Consider defining a bean of type 'graphql.GraphQL' in your configuration.

I tried to swap the dependency as suggested in this discussion but nothing works, I still get the same error. And as in your closing comment above, I don\t see the version 1.18 has been released yet.
Any idea how to resolve this issue?

**Comment by etienne-sf** [comment]
The ´graphql-java-runtime´ is the reason of the issue, as it is a mix of the client and server runtime : the ´graphql.GraphQL´ exists only on server side, but was wrongly needed on some client configurations. 

It doesn't exist since the 1.18.1. 

You should use the 1.18.6 (last released) of the ´graphql-java-client-runtime´ instead. 

Étienne

**Comment by amar-shinde** [comment]
Hello Étienne,

When I add ´graphql-java-client-runtime´ dependency (version 1.18.6 / 1.18.7) then the generated code has extra enum definition and that fails with a message.
"GraphQLField cannot be resolved to a type" 

That error is shown for most of all the generated classes. Any idea what may be going wrong here?

Thanks & Warm Regards,
Amar

**Comment by etienne-sf** [comment]
Hello,

You added a comment to a closed thread, that is probably unrelated to dour issue. 

Can you start a new thread, and describe the plug-in configuration you are using ?

Étienne
