### ISSUE TITLE
Generated clients don't support array field arguments

### ISSUE THREAD

**Issue by kalinwilson** [graphql-java-generator/graphql-maven-plugin-project#65]
Given a schema with a type defined as:
type MyType {
  id: ID!
  name: String!
  subObject(types: [SubObjectTypes!]): SubObject
}
where SubObject and SubObjectType (an enum) are also defined.

And a query defined as:
getMyType(id: ID!): MyType

In the generated client for this schema, issuing a query executor request with the following partial query string fails:
String queryString = "{id name subObject(types: [TYPE1, TYPE2])}"
MyType myType = schemaQueryExecutor(queryString, "THE_ID");

The request fails with a GraphQLRequesttPreparationException saying the argument field couldn't be read. If I get rid of the array brackets, and only provide one value (to make the GraphQL client happy with the syntax), the request succeeds.

The generated code for the subObject field likely has these annotations:
@JsonProperty("subObject")
	@JsonDeserialize(using = CustomJacksonDeserializers.ListSubObject.class)
	@GraphQLInputParameters(names = {"types"}, types = {"SubObjectType"})
	@GraphQLNonScalar(fieldName = "subObject", graphQLTypeSimpleName = "SubObject", javaClass = SubObject.class)
I don't see that these annotations indicate that the input parameters will be a list of values.

**Comment by etienne-sf** [comment]
Hello,

  Currently, the support for parameters as array is only possible through a query parameter.

You should do something like this:

```
// Build in Java the list that you want as a parameter for the subObject field
List<SubObjectTypes> types = new ArrayList<>();
types.add(SubObjectTypes.builder().withType(TYPE1).build());
types.add(SubObjectTypes.builder().withType(TYPE2).build());

// Have an input parameter instead of the list in the text query:
String queryString = "{id name subObject(types: &myParameter)}"

// Pass the input parameter's name then its value:
MyType myType = schemaQueryExecutor(queryString, "THE_ID", "myParameter", types);
```

As you're not the first to encounter this, it means I should either:
* Allow the kind of query you attempted. But it's complex. I'll think around that one.
* Add some more info about that, in the error message, to guide the developper.

I'll give a try to the second one, to begin with.

Etienne

**Comment by etienne-sf** [comment]
I added a specific error message, in this case, which explains what how to properly use a Bind Parameter

**Comment by kalinwilson** [comment]
The error message is still only a stop-gap. My use case it to forward my client requests to other servers via your client, so I need your client to support the GraphQL query syntax. I'm not building canned, precompiled queries. If my server receives a valid request, I should be able to use that request, or a part of it,  as the full or partial query string in a client call (V11.2.1)

**Comment by etienne-sf** [comment]
This is solved in the 1.13 release.

Can you confirm that?

**Comment by cmenetrier** [comment]
Hi, 
I've a similar use case and can unfortunately confirm that the issue is not solved with release 1.14.
String values passed inside a list are indeed not escaped properly , which breaks the global json being sent.

**Comment by etienne-sf** [comment]
Right, I see. 

I'll check and correct with string escapes.

**Comment by etienne-sf** [comment]
Right, I made a wrong assumption on this one.
So the tests were OK, but a correct graphiql Request would not work: as you stated, a copy/paste valid request from graphiql, that would contain strings, would not be properly escaped.

This correction will be available in the next

**Comment by etienne-sf** [comment]
Can you check the 1.14.1 release ?

It solves this issue

**Comment by cmenetrier** [comment]
Yes, I confirm that 1.14.1 solves the issue

**Comment by etienne-sf** [comment]
Great !
